import js from '@eslint/js';

export default [
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      '.wrangler/**',
      '.vite/**',
      'assets/**',
      'PROJECT_TEMPLATE.js',
      'QUICK_REFERENCE.js',
    ],
  },
  js.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      ecmaVersion: 2024,
      sourceType: 'module',
      globals: {
        AbortController: 'readonly',
        AbortSignal: 'readonly',
        Blob: 'readonly',
        caches: 'readonly',
        cancelAnimationFrame: 'readonly',
        Chart: 'readonly',
        console: 'readonly',
        crypto: 'readonly',
        dataLayer: 'writable',
        document: 'readonly',
        fetch: 'readonly',
        Globe: 'readonly',
        gtag: 'readonly',
        history: 'readonly',
        Image: 'readonly',
        Intl: 'readonly',
        IntersectionObserver: 'readonly',
        localStorage: 'readonly',
        location: 'readonly',
        module: 'readonly',
        navigator: 'readonly',
        performance: 'readonly',
        process: 'readonly',
        projects: 'readonly',
        requestAnimationFrame: 'readonly',
        Response: 'readonly',
        require: 'readonly',
        sessionStorage: 'readonly',
        self: 'readonly',
        setInterval: 'readonly',
        setTimeout: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        URL: 'readonly',
        URLSearchParams: 'readonly',
        WebcamManager: 'readonly',
        WEBCAM_DATA: 'readonly',
        window: 'readonly',
        __dirname: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': ['warn', { argsIgnorePattern: '^_', caughtErrorsIgnorePattern: '^_' }],
      'no-empty': ['error', { allowEmptyCatch: true }],
    },
  },
];
